CARDS = {
    "Sapling": {
        "name":"Sapling",
        "attack": 0,
        "hp": 2,
        "types": ["diurnal", "immobile"],
        "skills": [],
    },
    "Sap-king": {
        "name":"Sap-king",
        "attack": 0,
        "hp": 20,
        "types": ["diurnal", "immobile"],
        "skills": [],
    },
    "Weeping Willow": {
        "name":"Weeping Willow",
        "attack": 2,
        "hp": 10,
        "types": ["diurnal", "immobile"],
        "skills": [],
    },
    "Doctor Apple": {
        "name":"Doctor Apple",
        "attack": 10,
        "hp": 10,
        "types": ["diurnal", "immobile", "healer"],
        "skills": [],
    },
    "Cacti Warrior": {
        "name":"Cacti Warrior",
        "attack": 10,
        "hp": 4,
        "types": ["diurnal", "arid"],
        "skills": [],
    },
    "Cacti Assassin": {
        "name":"Cacti Assassin",
        "attack": 22,
        "hp": 8,
        "types": ["diurnal", "arid"],
        "skills": [],
    },
    "Chirpsly": {
        "name":"Chirpsly",
        "attack": 4,
        "hp": 3,
        "types": ["flying"],
        "skills": [],
    },
    "Honk": {
        "name":"Honk",
        "attack": 10,
        "hp": 4,
        "types": ["flying", "water"],
        "skills": [],
    },
    "Fernando": {
        "name":"Fernando",
        "attack": 7,
        "hp": 7,
        "types": ["flying", "cool"],
        "skills": [],
    },
    "Spitdevil": {
        "name":"Spitdevil",
        "attack": 4,
        "hp": 2,
        "types": ["demon", "offensive"],
        "skills": [],
    },
    "Lil' Devin": {
        "name":"Lil' Devin",
        "attack": 6,
        "hp": 1,
        "types": ["demon", "tiny"],
        "skills": [],
    },
    "Dort": {
        "name":"Dort",
        "attack": 5,
        "hp": 2,
        "types": ["demon"],
        "skills": [],
    },
    "Bloodman": {
        "name":"Bloodman",
        "attack": 2,
        "hp": 10,
        "types": ["demon", "healer"],
        "skills": [],
    },
    "Sick Worm": {
        "name":"Sick Worm",
        "attack": 3,
        "hp": 2,
        "types": ["demon", "cool"],
        "skills": [],
    },
    "Demon Lord": {
        "name":"Demon Lord",
        "attack": 33,
        "hp": 10,
        "types": ["demon"],
        "skills": [],
    },
    "Brown Mushy": {
        "name":"Brown Mushy",
        "attack": 4,
        "hp": 1,
        "types": ["nocturnal", "immobile"],
        "skills": [],
    },
    "Amanita": {
        "name":"Amanita",
        "attack": 8,
        "hp": 3,
        "types": ["nocturnal", "immobile"],
        "skills": [],
    },
    "Great Mycelios": {
        "name":"Great Mycelios",
        "attack": 0,
        "hp": 20,
        "types": ["nocturnal"],
        "skills": [], # removes immobile from adjacent nocturnal cards
    },
    "Momorel": {
        "name":"Momorel",
        "attack": 5,
        "hp": 5,
        "types": ["nocturnal", "healer", "immobile"],
        "skills": [],
    },
    "Sporrior": {
        "name":"Sporrior",
        "attack": 9,
        "hp": 2,
        "types": ["nocturnal", "flying"],
        "skills": [],
    },
    "Talons": {
        "name":"Talons",
        "attack": 9,
        "hp": 9,
        "types": ["dragon", "flying"],
        "skills": [],
    },
    "Gourmogon": {
        "name":"Gourmogon",
        "attack": 4,
        "hp": 20,
        "types": ["dragon", "cool"],
        "skills": [],
    },
}