ASSET_PATH = "classes/assets/"

TOP = 0
RIGHT = 1
BOTTOM = 2
LEFT = 3

TYPES = {
    "grass": "grass",
    "hills": "grass",
    "mountains": "grass",
    "trees": "grass",
    #"hellscape": "grass",
    #"desert": "grass",
    #"snow": "grass",
    #"pit": "pit",
    "water": "water",
    "hellscape": "hellscape",
    "desert": "desert",
    "snow": "snow",
    "enchanted": "trans",
    "clouds": "trans",
    "pit": "trans",
    # "water": "water",
}
PRIORITY = {
    "grass": 1,
    "desert": 2,
    "snow": 3,
    "hellscape": 4,
    "trans": 999,
    "water": 0,
}

NEXT_LAYER = {"water": "grass",
              "grass" : "desert",
                "desert" : "snow",
          "snow": "hellscape",
          "hellscape": "trans"}

EXEMPT = {
    "pit",
}

BIG_BOARD_TILES = {
    "grass": "board/grass1.png",
    "hills": "board/hills1.png",
    "trees": "board/trees1.png",
    "mountains": "board/mountains1.png",
    "water": "board/water1.png",
    "desert": "board/desert1.png",
    "snow": "board/snow1.png",
    "hellscape": "board/hellscape1.png",
    "enchanted": "board/enchanted1.png",
    "clouds": "board/clouds1.png",
    "pit": "board/pit.png",
}

BOARD_TILES_0 = {
    "grass": {
        "grass-0-grass-1-grass-2-grass-3":
            [
                "board/grass1.png",
                "board/grass-a1.png",
                "board/grass-f1.png",
                "board/grass-f2.png",
                "board/grass-f3.png",
                "board/grass-f4.png",
                "board/grass-f5.png",
                "board/grass-f6.png",
            ],
        "water-0-water-1-water-2-water-3": ["board/grass2.png", "board/grass-a2.png",],
        "grass-0-water-1-grass-2-grass-3": ["board/grass3.png", "board/grass-a3.png",],
        "grass-0-grass-1-water-2-grass-3": ["board/grass4.png", "board/grass-a4.png",],
        "grass-0-grass-1-grass-2-water-3": ["board/grass5.png", "board/grass-a5.png",],
        "water-0-grass-1-grass-2-grass-3": ["board/grass6.png", "board/grass-a6.png",],
        "water-0-water-1-grass-2-water-3": ["board/grass7.png", "board/grass-a7.png",],
        "water-0-water-1-water-2-grass-3": ["board/grass8.png", "board/grass-a8.png",],
        "water-0-grass-1-water-2-water-3": ["board/grass9.png", "board/grass-a9.png",],
        "grass-0-water-1-water-2-water-3": ["board/grass10.png", "board/grass-a10.png",],
        "water-0-grass-1-grass-2-water-3": ["board/grass11.png", "board/grass-a11.png",],
        "grass-0-grass-1-water-2-water-3": ["board/grass12.png", "board/grass-a12.png",],
        "water-0-water-1-grass-2-grass-3": ["board/grass13.png", "board/grass-a13.png",],
        "grass-0-water-1-water-2-grass-3": ["board/grass14.png", "board/grass-a14.png",],
        "water-0-grass-1-water-2-grass-3": ["board/grass16.png", "board/grass-a16.png",],
        "grass-0-water-1-grass-2-water-3": ["board/grass15.png", "board/grass-a15.png",],
    },
    "hills": {
        "grass-0-grass-1-grass-2-grass-3": ["board/hills1.png",],
        "water-0-water-1-water-2-water-3": ["board/hills2.png",],
        "grass-0-water-1-grass-2-grass-3": ["board/hills3.png",],
        "grass-0-grass-1-water-2-grass-3": ["board/hills4.png",],
        "grass-0-grass-1-grass-2-water-3": ["board/hills5.png",],
        "water-0-grass-1-grass-2-grass-3": ["board/hills6.png",],
        "water-0-water-1-grass-2-water-3": ["board/hills7.png",],
        "water-0-water-1-water-2-grass-3": ["board/hills8.png",],
        "water-0-grass-1-water-2-water-3": ["board/hills9.png",],
        "grass-0-water-1-water-2-water-3": ["board/hills10.png",],
        "water-0-grass-1-grass-2-water-3": ["board/hills11.png",],
        "grass-0-grass-1-water-2-water-3": ["board/hills12.png",],
        "water-0-water-1-grass-2-grass-3": ["board/hills13.png",],
        "grass-0-water-1-water-2-grass-3": ["board/hills14.png",],
        "water-0-grass-1-water-2-grass-3": ["board/hills2.png",],
        "grass-0-water-1-grass-2-water-3": ["board/hills2.png",],
        },
    "trees": {
        "grass-0-grass-1-grass-2-grass-3": ["board/trees1.png",],
        "water-0-water-1-water-2-water-3": ["board/trees2.png",],
        "grass-0-water-1-grass-2-grass-3": ["board/trees3.png",],
        "grass-0-grass-1-water-2-grass-3": ["board/trees4.png",],
        "grass-0-grass-1-grass-2-water-3": ["board/trees5.png",],
        "water-0-grass-1-grass-2-grass-3": ["board/trees6.png",],
        "water-0-water-1-grass-2-water-3": ["board/trees7.png",],
        "water-0-water-1-water-2-grass-3": ["board/trees8.png",],
        "water-0-grass-1-water-2-water-3": ["board/trees9.png",],
        "grass-0-water-1-water-2-water-3": ["board/trees10.png",],
        "water-0-grass-1-grass-2-water-3": ["board/trees11.png",],
        "grass-0-grass-1-water-2-water-3": ["board/trees12.png",],
        "water-0-water-1-grass-2-grass-3": ["board/trees13.png",],
        "grass-0-water-1-water-2-grass-3": ["board/trees14.png",],
        "water-0-grass-1-water-2-grass-3": ["board/trees16.png",],
        "grass-0-water-1-grass-2-water-3": ["board/trees15.png",],
        },
    "mountains": {
        "grass-0-grass-1-grass-2-grass-3": ["board/mountains1.png",],
        "water-0-water-1-water-2-water-3": ["board/mountains1.png",],
        "grass-0-water-1-grass-2-grass-3": ["board/mountains1.png",],
        "grass-0-grass-1-water-2-grass-3": ["board/mountains1.png",],
        "grass-0-grass-1-grass-2-water-3": ["board/mountains1.png",],
        "water-0-grass-1-grass-2-grass-3": ["board/mountains1.png",],
        "water-0-water-1-grass-2-water-3": ["board/mountains1.png",],
        "water-0-water-1-water-2-grass-3": ["board/mountains1.png",],
        "water-0-grass-1-water-2-water-3": ["board/mountains1.png",],
        "grass-0-water-1-water-2-water-3": ["board/mountains1.png",],
        "water-0-grass-1-grass-2-water-3": ["board/mountains1.png",],
        "grass-0-grass-1-water-2-water-3": ["board/mountains1.png",],
        "water-0-water-1-grass-2-grass-3": ["board/mountains1.png",],
        "grass-0-water-1-water-2-grass-3": ["board/mountains1.png",],
        "water-0-grass-1-water-2-grass-3": ["board/mountains1.png",],
        "grass-0-water-1-grass-2-water-3": ["board/mountains1.png",],
    },
    "snow": {
        "snow-0-snow-1-snow-2-snow-3": ["board/snow1.png",],
        "trans-0-snow-1-snow-2-snow-3": ["board/snow2.png",],
        "snow-0-trans-1-snow-2-snow-3": ["board/snow3.png",],
        "snow-0-snow-1-trans-2-snow-3": ["board/snow4.png",],
        "snow-0-snow-1-snow-2-trans-3": ["board/snow5.png",],
        "trans-0-trans-1-snow-2-snow-3": ["board/snow6.png",],
        "snow-0-trans-1-trans-2-snow-3": ["board/snow7.png",],
        "snow-0-snow-1-trans-2-trans-3": ["board/snow8.png",],
        "trans-0-snow-1-snow-2-trans-3": ["board/snow9.png",],
        "snow-0-trans-1-snow-2-trans-3": ["board/snow10.png",],
        "trans-0-snow-1-trans-2-snow-3": ["board/snow11.png",],
        "trans-0-trans-1-trans-2-snow-3": ["board/snow12.png",],
        "snow-0-trans-1-trans-2-trans-3": ["board/snow13.png",],
        "trans-0-snow-1-trans-2-trans-3": ["board/snow14.png",],
        "trans-0-trans-1-snow-2-trans-3": ["board/snow15.png",],
        "trans-0-trans-1-trans-2-trans-3": ["board/snow16.png",],
        "water-0-water-1-water-2-water-3": ["board/snow17.png",],
        "snow-0-water-1-snow-2-snow-3": ["board/snow18.png",],
        "trans-0-water-1-snow-2-snow-3": ["board/snow19.png",],
        "snow-0-water-1-trans-2-snow-3": ["board/snow20.png",],
        "snow-0-water-1-snow-2-trans-3": ["board/snow21.png",],
        "trans-0-water-1-trans-2-snow-3": ["board/snow22.png",],
        "snow-0-water-1-trans-2-trans-3": ["board/snow23.png",],
        "trans-0-water-1-snow-2-trans-3": ["board/snow24.png",],
        "trans-0-water-1-trans-2-trans-3": ["board/snow25.png",],
        "snow-0-snow-1-water-2-snow-3": ["board/snow26.png",],
        "trans-0-snow-1-water-2-snow-3": ["board/snow27.png",],
        "snow-0-trans-1-water-2-snow-3": ["board/snow28.png",],
        "snow-0-snow-1-water-2-trans-3": ["board/snow29.png",],
        "trans-0-trans-1-water-2-snow-3": ["board/snow30.png",],
        "snow-0-trans-1-water-2-trans-3": ["board/snow31.png",],
        "trans-0-snow-1-water-2-trans-3": ["board/snow32.png",],
        "trans-0-trans-1-water-2-trans-3": ["board/snow33.png",],
        "snow-0-snow-1-snow-2-water-3": ["board/snow34.png",],
        "trans-0-snow-1-snow-2-water-3": ["board/snow35.png",],
        "snow-0-trans-1-snow-2-water-3": ["board/snow36.png",],
        "snow-0-snow-1-trans-2-water-3": ["board/snow37.png",],
        "trans-0-trans-1-snow-2-water-3": ["board/snow38.png",],
        "snow-0-trans-1-trans-2-water-3": ["board/snow39.png",],
        "trans-0-snow-1-trans-2-water-3": ["board/snow40.png",],
        "trans-0-trans-1-trans-2-water-3": ["board/snow41.png",],
        "water-0-snow-1-snow-2-snow-3": ["board/snow42.png",],
        "water-0-trans-1-snow-2-snow-3": ["board/snow43.png",],
        "water-0-snow-1-trans-2-snow-3": ["board/snow44.png",],
        "water-0-snow-1-snow-2-trans-3": ["board/snow45.png",],
        "water-0-trans-1-trans-2-snow-3": ["board/snow46.png",],
        "water-0-snow-1-trans-2-trans-3": ["board/snow47.png",],
        "water-0-trans-1-snow-2-trans-3": ["board/snow48.png",],
        "water-0-trans-1-trans-2-trans-3": ["board/snow49.png",],
        "water-0-water-1-snow-2-water-3": ["board/snow50.png",],
        "water-0-water-1-trans-2-water-3": ["board/snow51.png",],
        "water-0-water-1-water-2-snow-3": ["board/snow52.png",],
        "water-0-water-1-water-2-trans-3": ["board/snow53.png",],
        "water-0-snow-1-water-2-water-3": ["board/snow54.png",],
        "water-0-trans-1-water-2-water-3": ["board/snow55.png",],
        "snow-0-water-1-water-2-water-3": ["board/snow56.png",],
        "trans-0-water-1-water-2-water-3": ["board/snow57.png",],
        "water-0-snow-1-snow-2-water-3": ["board/snow58.png",],
        "water-0-trans-1-snow-2-water-3": ["board/snow59.png",],
        "water-0-snow-1-trans-2-water-3": ["board/snow60.png",],
        "water-0-trans-1-trans-2-water-3": ["board/snow61.png",],
        "snow-0-snow-1-water-2-water-3": ["board/snow62.png",],
        "trans-0-snow-1-water-2-water-3": ["board/snow63.png",],
        "snow-0-trans-1-water-2-water-3": ["board/snow64.png",],
        "trans-0-trans-1-water-2-water-3": ["board/snow65.png",],
        "water-0-water-1-snow-2-snow-3": ["board/snow66.png",],
        "water-0-water-1-trans-2-snow-3": ["board/snow67.png",],
        "water-0-water-1-snow-2-trans-3": ["board/snow68.png",],
        "water-0-water-1-trans-2-trans-3": ["board/snow69.png",],
        "snow-0-water-1-water-2-snow-3": ["board/snow70.png",],
        "trans-0-water-1-water-2-snow-3": ["board/snow72.png",],
        "snow-0-water-1-water-2-trans-3": ["board/snow71.png",],
        "trans-0-water-1-water-2-trans-3": ["board/snow73.png",],
        "snow-0-water-1-snow-2-water-3": ["board/snow74.png",],
        "trans-0-water-1-snow-2-water-3": ["board/snow75.png",],
        "snow-0-water-1-trans-2-water-3": ["board/snow76.png",],
        "trans-0-water-1-trans-2-water-3": ["board/snow77.png",],
        "water-0-snow-1-water-2-snow-3": ["board/snow78.png",],
        "water-0-trans-1-water-2-snow-3": ["board/snow79.png",],
        "water-0-snow-1-water-2-trans-3": ["board/snow80.png",],
        "water-0-trans-1-water-2-trans-3": ["board/snow81.png",],
        },
    "hellscape": {
        "hellscape-0-hellscape-1-hellscape-2-hellscape-3": ["board/hellscape1.png",],
        "trans-0-hellscape-1-hellscape-2-hellscape-3": ["board/hellscape2.png",],
        "hellscape-0-trans-1-hellscape-2-hellscape-3": ["board/hellscape3.png",],
        "hellscape-0-hellscape-1-trans-2-hellscape-3": ["board/hellscape4.png",],
        "hellscape-0-hellscape-1-hellscape-2-trans-3": ["board/hellscape5.png",],
        "trans-0-trans-1-hellscape-2-hellscape-3": ["board/hellscape6.png",],
        "hellscape-0-trans-1-trans-2-hellscape-3": ["board/hellscape7.png",],
        "hellscape-0-hellscape-1-trans-2-trans-3": ["board/hellscape8.png",],
        "trans-0-hellscape-1-hellscape-2-trans-3": ["board/hellscape9.png",],
        "hellscape-0-trans-1-hellscape-2-trans-3": ["board/hellscape10.png",],
        "trans-0-hellscape-1-trans-2-hellscape-3": ["board/hellscape11.png",],
        "trans-0-trans-1-trans-2-hellscape-3": ["board/hellscape12.png",],
        "hellscape-0-trans-1-trans-2-trans-3": ["board/hellscape13.png",],
        "trans-0-hellscape-1-trans-2-trans-3": ["board/hellscape14.png",],
        "trans-0-trans-1-hellscape-2-trans-3": ["board/hellscape15.png",],
        "trans-0-trans-1-trans-2-trans-3": ["board/hellscape16.png",],
        "water-0-water-1-water-2-water-3": ["board/hellscape17.png",],
        "hellscape-0-water-1-hellscape-2-hellscape-3": ["board/hellscape18.png",],
        "trans-0-water-1-hellscape-2-hellscape-3": ["board/hellscape19.png",],
        "hellscape-0-water-1-trans-2-hellscape-3": ["board/hellscape20.png",],
        "hellscape-0-water-1-hellscape-2-trans-3": ["board/hellscape21.png",],
        "trans-0-water-1-trans-2-hellscape-3": ["board/hellscape22.png",],
        "hellscape-0-water-1-trans-2-trans-3": ["board/hellscape23.png",],
        "trans-0-water-1-hellscape-2-trans-3": ["board/hellscape24.png",],
        "trans-0-water-1-trans-2-trans-3": ["board/hellscape25.png",],
        "hellscape-0-hellscape-1-water-2-hellscape-3": ["board/hellscape26.png",],
        "trans-0-hellscape-1-water-2-hellscape-3": ["board/hellscape27.png",],
        "hellscape-0-trans-1-water-2-hellscape-3": ["board/hellscape28.png",],
        "hellscape-0-hellscape-1-water-2-trans-3": ["board/hellscape29.png",],
        "trans-0-trans-1-water-2-hellscape-3": ["board/hellscape30.png",],
        "hellscape-0-trans-1-water-2-trans-3": ["board/hellscape31.png",],
        "trans-0-hellscape-1-water-2-trans-3": ["board/hellscape32.png",],
        "trans-0-trans-1-water-2-trans-3": ["board/hellscape33.png",],
        "hellscape-0-hellscape-1-hellscape-2-water-3": ["board/hellscape34.png",],
        "trans-0-hellscape-1-hellscape-2-water-3": ["board/hellscape35.png",],
        "hellscape-0-trans-1-hellscape-2-water-3": ["board/hellscape36.png",],
        "hellscape-0-hellscape-1-trans-2-water-3": ["board/hellscape37.png",],
        "trans-0-trans-1-hellscape-2-water-3": ["board/hellscape38.png",],
        "hellscape-0-trans-1-trans-2-water-3": ["board/hellscape39.png",],
        "trans-0-hellscape-1-trans-2-water-3": ["board/hellscape40.png",],
        "trans-0-trans-1-trans-2-water-3": ["board/hellscape41.png",],
        "water-0-hellscape-1-hellscape-2-hellscape-3": ["board/hellscape42.png",],
        "water-0-trans-1-hellscape-2-hellscape-3": ["board/hellscape43.png",],
        "water-0-hellscape-1-trans-2-hellscape-3": ["board/hellscape44.png",],
        "water-0-hellscape-1-hellscape-2-trans-3": ["board/hellscape45.png",],
        "water-0-trans-1-trans-2-hellscape-3": ["board/hellscape46.png",],
        "water-0-hellscape-1-trans-2-trans-3": ["board/hellscape47.png",],
        "water-0-trans-1-hellscape-2-trans-3": ["board/hellscape48.png",],
        "water-0-trans-1-trans-2-trans-3": ["board/hellscape49.png",],
        "water-0-water-1-hellscape-2-water-3": ["board/hellscape50.png",],
        "water-0-water-1-trans-2-water-3": ["board/hellscape51.png",],
        "water-0-water-1-water-2-hellscape-3": ["board/hellscape52.png",],
        "water-0-water-1-water-2-trans-3": ["board/hellscape53.png",],
        "water-0-hellscape-1-water-2-water-3": ["board/hellscape54.png",],
        "water-0-trans-1-water-2-water-3": ["board/hellscape55.png",],
        "hellscape-0-water-1-water-2-water-3": ["board/hellscape56.png",],
        "trans-0-water-1-water-2-water-3": ["board/hellscape57.png",],
        "water-0-hellscape-1-hellscape-2-water-3": ["board/hellscape58.png",],
        "water-0-trans-1-hellscape-2-water-3": ["board/hellscape59.png",],
        "water-0-hellscape-1-trans-2-water-3": ["board/hellscape60.png",],
        "water-0-trans-1-trans-2-water-3": ["board/hellscape61.png",],
        "hellscape-0-hellscape-1-water-2-water-3": ["board/hellscape62.png",],
        "trans-0-hellscape-1-water-2-water-3": ["board/hellscape63.png",],
        "hellscape-0-trans-1-water-2-water-3": ["board/hellscape64.png",],
        "trans-0-trans-1-water-2-water-3": ["board/hellscape65.png",],
        "water-0-water-1-hellscape-2-hellscape-3": ["board/hellscape66.png",],
        "water-0-water-1-trans-2-hellscape-3": ["board/hellscape67.png",],
        "water-0-water-1-hellscape-2-trans-3": ["board/hellscape68.png",],
        "water-0-water-1-trans-2-trans-3": ["board/hellscape69.png",],
        "hellscape-0-water-1-water-2-hellscape-3": ["board/hellscape70.png",],
        "trans-0-water-1-water-2-hellscape-3": ["board/hellscape72.png",],
        "hellscape-0-water-1-water-2-trans-3": ["board/hellscape71.png",],
        "trans-0-water-1-water-2-trans-3": ["board/hellscape73.png",],
        "hellscape-0-water-1-hellscape-2-water-3": ["board/hellscape74.png",],
        "trans-0-water-1-hellscape-2-water-3": ["board/hellscape75.png",],
        "hellscape-0-water-1-trans-2-water-3": ["board/hellscape76.png",],
        "trans-0-water-1-trans-2-water-3": ["board/hellscape77.png",],
        "water-0-hellscape-1-water-2-hellscape-3": ["board/hellscape78.png",],
        "water-0-trans-1-water-2-hellscape-3": ["board/hellscape79.png",],
        "water-0-hellscape-1-water-2-trans-3": ["board/hellscape80.png",],
        "water-0-trans-1-water-2-trans-3": ["board/hellscape81.png",],
        },
        # {
        # "grass-0-grass-1-grass-2-grass-3": ["board/hellscape1.png",],
        # "water-0-water-1-water-2-water-3": ["board/hellscape2.png",],
        # "grass-0-water-1-grass-2-grass-3": ["board/hellscape3.png",],
        # "grass-0-grass-1-water-2-grass-3": ["board/hellscape4.png",],
        # "grass-0-grass-1-grass-2-water-3": ["board/hellscape5.png",],
        # "water-0-grass-1-grass-2-grass-3": ["board/hellscape6.png",],
        # "water-0-water-1-grass-2-water-3": ["board/hellscape7.png",],
        # "water-0-water-1-water-2-grass-3": ["board/hellscape8.png",],
        # "water-0-grass-1-water-2-water-3": ["board/hellscape9.png",],
        # "grass-0-water-1-water-2-water-3": ["board/hellscape10.png",],
        # "water-0-grass-1-grass-2-water-3": ["board/hellscape11.png",],
        # "grass-0-grass-1-water-2-water-3": ["board/hellscape12.png",],
        # "water-0-water-1-grass-2-grass-3": ["board/hellscape13.png",],
        # "grass-0-water-1-water-2-grass-3": ["board/hellscape14.png",],
        # "water-0-grass-1-water-2-grass-3": ["board/hellscape16.png",],
        # "grass-0-water-1-grass-2-water-3": ["board/hellscape15.png",],
        # },
    "pit": {
       "trans-0-trans-1-trans-2-trans-3": ["board/pit.png",],
    },
    "water": {
        "water-0-water-1-water-2-water-3": ["board/water1.png",],
    },
    "desert": {
        "desert-0-desert-1-desert-2-desert-3": ["board/desert1.png","board/desert1.png","board/desert1.png","board/desert1.png","board/desert1.png","board/desert1.png","board/desert1.png","board/desert1.png","board/desert1.png","board/desert1.png",],
        "trans-0-desert-1-desert-2-desert-3": ["board/desert2.png",],
        "desert-0-trans-1-desert-2-desert-3": ["board/desert3.png",],
        "desert-0-desert-1-trans-2-desert-3": ["board/desert4.png",],
        "desert-0-desert-1-desert-2-trans-3": ["board/desert5.png",],
        "trans-0-trans-1-desert-2-desert-3": ["board/desert6.png",],
        "desert-0-trans-1-trans-2-desert-3": ["board/desert7.png",],
        "desert-0-desert-1-trans-2-trans-3": ["board/desert8.png",],
        "trans-0-desert-1-desert-2-trans-3": ["board/desert9.png",],
        "desert-0-trans-1-desert-2-trans-3": ["board/desert10.png",],
        "trans-0-desert-1-trans-2-desert-3": ["board/desert11.png",],
        "trans-0-trans-1-trans-2-desert-3": ["board/desert12.png",],
        "desert-0-trans-1-trans-2-trans-3": ["board/desert13.png",],
        "trans-0-desert-1-trans-2-trans-3": ["board/desert14.png",],
        "trans-0-trans-1-desert-2-trans-3": ["board/desert15.png",],
        "trans-0-trans-1-trans-2-trans-3": ["board/desert16.png",],
        "water-0-water-1-water-2-water-3": ["board/deser-a1.png","board/deser-a2.png","board/deser-a3.png","board/deser-a4.png","board/deser-a5.png",],
        "desert-0-water-1-desert-2-desert-3": ["board/desert18.png",],
        "trans-0-water-1-desert-2-desert-3": ["board/desert19.png",],
        "desert-0-water-1-trans-2-desert-3": ["board/desert20.png",],
        "desert-0-water-1-desert-2-trans-3": ["board/desert21.png",],
        "trans-0-water-1-trans-2-desert-3": ["board/desert22.png",],
        "desert-0-water-1-trans-2-trans-3": ["board/desert23.png",],
        "trans-0-water-1-desert-2-trans-3": ["board/desert24.png",],
        "trans-0-water-1-trans-2-trans-3": ["board/desert25.png",],
        "desert-0-desert-1-water-2-desert-3": ["board/desert26.png",],
        "trans-0-desert-1-water-2-desert-3": ["board/desert27.png",],
        "desert-0-trans-1-water-2-desert-3": ["board/desert28.png",],
        "desert-0-desert-1-water-2-trans-3": ["board/desert29.png",],
        "trans-0-trans-1-water-2-desert-3": ["board/desert30.png",],
        "desert-0-trans-1-water-2-trans-3": ["board/desert31.png",],
        "trans-0-desert-1-water-2-trans-3": ["board/desert32.png",],
        "trans-0-trans-1-water-2-trans-3": ["board/desert33.png",],
        "desert-0-desert-1-desert-2-water-3": ["board/desert34.png",],
        "trans-0-desert-1-desert-2-water-3": ["board/desert35.png",],
        "desert-0-trans-1-desert-2-water-3": ["board/desert36.png",],
        "desert-0-desert-1-trans-2-water-3": ["board/desert37.png",],
        "trans-0-trans-1-desert-2-water-3": ["board/desert38.png",],
        "desert-0-trans-1-trans-2-water-3": ["board/desert39.png",],
        "trans-0-desert-1-trans-2-water-3": ["board/desert40.png",],
        "trans-0-trans-1-trans-2-water-3": ["board/desert41.png",],
        "water-0-desert-1-desert-2-desert-3": ["board/desert42.png",],
        "water-0-trans-1-desert-2-desert-3": ["board/desert43.png",],
        "water-0-desert-1-trans-2-desert-3": ["board/desert44.png",],
        "water-0-desert-1-desert-2-trans-3": ["board/desert45.png",],
        "water-0-trans-1-trans-2-desert-3": ["board/desert46.png",],
        "water-0-desert-1-trans-2-trans-3": ["board/desert47.png",],
        "water-0-trans-1-desert-2-trans-3": ["board/desert48.png",],
        "water-0-trans-1-trans-2-trans-3": ["board/desert49.png",],
        "water-0-water-1-desert-2-water-3": ["board/desert50.png",],
        "water-0-water-1-trans-2-water-3": ["board/desert51.png",],
        "water-0-water-1-water-2-desert-3": ["board/desert52.png",],
        "water-0-water-1-water-2-trans-3": ["board/desert53.png",],
        "water-0-desert-1-water-2-water-3": ["board/desert54.png",],
        "water-0-trans-1-water-2-water-3": ["board/desert55.png",],
        "desert-0-water-1-water-2-water-3": ["board/desert56.png",],
        "trans-0-water-1-water-2-water-3": ["board/desert57.png",],
        "water-0-desert-1-desert-2-water-3": ["board/desert58.png",],
        "water-0-trans-1-desert-2-water-3": ["board/desert59.png",],
        "water-0-desert-1-trans-2-water-3": ["board/desert60.png",],
        "water-0-trans-1-trans-2-water-3": ["board/desert61.png",],
        "desert-0-desert-1-water-2-water-3": ["board/desert62.png",],
        "trans-0-desert-1-water-2-water-3": ["board/desert63.png",],
        "desert-0-trans-1-water-2-water-3": ["board/desert64.png",],
        "trans-0-trans-1-water-2-water-3": ["board/desert65.png",],
        "water-0-water-1-desert-2-desert-3": ["board/desert66.png",],
        "water-0-water-1-trans-2-desert-3": ["board/desert67.png",],
        "water-0-water-1-desert-2-trans-3": ["board/desert68.png",],
        "water-0-water-1-trans-2-trans-3": ["board/desert69.png",],
        "desert-0-water-1-water-2-desert-3": ["board/desert70.png",],
        "trans-0-water-1-water-2-desert-3": ["board/desert72.png",],
        "desert-0-water-1-water-2-trans-3": ["board/desert71.png",],
        "trans-0-water-1-water-2-trans-3": ["board/desert73.png",],
        "desert-0-water-1-desert-2-water-3": ["board/desert74.png",],
        "trans-0-water-1-desert-2-water-3": ["board/desert75.png",],
        "desert-0-water-1-trans-2-water-3": ["board/desert76.png",],
        "trans-0-water-1-trans-2-water-3": ["board/desert77.png",],
        "water-0-desert-1-water-2-desert-3": ["board/desert78.png",],
        "water-0-trans-1-water-2-desert-3": ["board/desert79.png",],
        "water-0-desert-1-water-2-trans-3": ["board/desert80.png",],
        "water-0-trans-1-water-2-trans-3": ["board/desert81.png",],
        },
    "enchanted":{
        "trans-0-trans-1-trans-2-trans-3": [
            "board/enchanted1.png",
            "board/enchanted2.png",
            "board/enchanted3.png",
            "board/enchanted4.png",
        ]
    },
    "clouds":{
        "trans-0-trans-1-trans-2-trans-3": [
            "board/clouds1.png",
            "board/clouds2.png",
            "board/clouds3.png",
            "board/clouds4.png",
        ]
    },
}

def add_alt_tiles(tiles_dict):
    for k in tiles_dict:
        if k in {"desert"}:
            for t in tiles_dict[k]:
                temp_list = tiles_dict[k][t]
                temp_list.append(temp_list[0].replace("desert", "desert-a"))
                temp_list.append(temp_list[0].replace("desert", "desert-a"))
                tiles_dict[k][t] = temp_list
    return tiles_dict


BOARD_TILES = add_alt_tiles(BOARD_TILES_0)


DUMMY_TILE = "stills/dummy.png"
TITLE_TILE = "stills/title.png"


